//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuakeMessage", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class QuakeMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeleteMeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DepthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaultTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatCalcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatCalc2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatCwField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatCw2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LonCalcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LonCalc2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LonCwField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LonCw2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MagnitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReference1.StationsInfo StationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StationsGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double StressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double StrikeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TopDepthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double WidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DeleteMe {
            get {
                return this.DeleteMeField;
            }
            set {
                if ((this.DeleteMeField.Equals(value) != true)) {
                    this.DeleteMeField = value;
                    this.RaisePropertyChanged("DeleteMe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Depth {
            get {
                return this.DepthField;
            }
            set {
                if ((this.DepthField.Equals(value) != true)) {
                    this.DepthField = value;
                    this.RaisePropertyChanged("Depth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Dip {
            get {
                return this.DipField;
            }
            set {
                if ((this.DipField.Equals(value) != true)) {
                    this.DipField = value;
                    this.RaisePropertyChanged("Dip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventID {
            get {
                return this.EventIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EventIDField, value) != true)) {
                    this.EventIDField = value;
                    this.RaisePropertyChanged("EventID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultType {
            get {
                return this.FaultTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultTypeField, value) != true)) {
                    this.FaultTypeField = value;
                    this.RaisePropertyChanged("FaultType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Flag {
            get {
                return this.FlagField;
            }
            set {
                if ((object.ReferenceEquals(this.FlagField, value) != true)) {
                    this.FlagField = value;
                    this.RaisePropertyChanged("Flag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Lat {
            get {
                return this.LatField;
            }
            set {
                if ((this.LatField.Equals(value) != true)) {
                    this.LatField = value;
                    this.RaisePropertyChanged("Lat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LatCalc {
            get {
                return this.LatCalcField;
            }
            set {
                if ((this.LatCalcField.Equals(value) != true)) {
                    this.LatCalcField = value;
                    this.RaisePropertyChanged("LatCalc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LatCalc2 {
            get {
                return this.LatCalc2Field;
            }
            set {
                if ((this.LatCalc2Field.Equals(value) != true)) {
                    this.LatCalc2Field = value;
                    this.RaisePropertyChanged("LatCalc2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LatCw {
            get {
                return this.LatCwField;
            }
            set {
                if ((this.LatCwField.Equals(value) != true)) {
                    this.LatCwField = value;
                    this.RaisePropertyChanged("LatCw");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LatCw2 {
            get {
                return this.LatCw2Field;
            }
            set {
                if ((this.LatCw2Field.Equals(value) != true)) {
                    this.LatCw2Field = value;
                    this.RaisePropertyChanged("LatCw2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Lon {
            get {
                return this.LonField;
            }
            set {
                if ((this.LonField.Equals(value) != true)) {
                    this.LonField = value;
                    this.RaisePropertyChanged("Lon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LonCalc {
            get {
                return this.LonCalcField;
            }
            set {
                if ((this.LonCalcField.Equals(value) != true)) {
                    this.LonCalcField = value;
                    this.RaisePropertyChanged("LonCalc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LonCalc2 {
            get {
                return this.LonCalc2Field;
            }
            set {
                if ((this.LonCalc2Field.Equals(value) != true)) {
                    this.LonCalc2Field = value;
                    this.RaisePropertyChanged("LonCalc2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LonCw {
            get {
                return this.LonCwField;
            }
            set {
                if ((this.LonCwField.Equals(value) != true)) {
                    this.LonCwField = value;
                    this.RaisePropertyChanged("LonCw");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LonCw2 {
            get {
                return this.LonCw2Field;
            }
            set {
                if ((this.LonCw2Field.Equals(value) != true)) {
                    this.LonCw2Field = value;
                    this.RaisePropertyChanged("LonCw2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Magnitude {
            get {
                return this.MagnitudeField;
            }
            set {
                if ((this.MagnitudeField.Equals(value) != true)) {
                    this.MagnitudeField = value;
                    this.RaisePropertyChanged("Magnitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.ServiceReference1.StationsInfo Station {
            get {
                return this.StationField;
            }
            set {
                if ((object.ReferenceEquals(this.StationField, value) != true)) {
                    this.StationField = value;
                    this.RaisePropertyChanged("Station");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StationCode {
            get {
                return this.StationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StationCodeField, value) != true)) {
                    this.StationCodeField = value;
                    this.RaisePropertyChanged("StationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StationsGroup {
            get {
                return this.StationsGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.StationsGroupField, value) != true)) {
                    this.StationsGroupField = value;
                    this.RaisePropertyChanged("StationsGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Stress {
            get {
                return this.StressField;
            }
            set {
                if ((this.StressField.Equals(value) != true)) {
                    this.StressField = value;
                    this.RaisePropertyChanged("Stress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Strike {
            get {
                return this.StrikeField;
            }
            set {
                if ((this.StrikeField.Equals(value) != true)) {
                    this.StrikeField = value;
                    this.RaisePropertyChanged("Strike");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TopDepth {
            get {
                return this.TopDepthField;
            }
            set {
                if ((this.TopDepthField.Equals(value) != true)) {
                    this.TopDepthField = value;
                    this.RaisePropertyChanged("TopDepth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StationsInfo", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class StationsInfo : ConsoleApplication1.ServiceReference1.TableServiceEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CrustalAmplificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ElevationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double KappaCoeffientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiteAmplificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoilConditionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrustalAmplification {
            get {
                return this.CrustalAmplificationField;
            }
            set {
                if ((object.ReferenceEquals(this.CrustalAmplificationField, value) != true)) {
                    this.CrustalAmplificationField = value;
                    this.RaisePropertyChanged("CrustalAmplification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Elevation {
            get {
                return this.ElevationField;
            }
            set {
                if ((this.ElevationField.Equals(value) != true)) {
                    this.ElevationField = value;
                    this.RaisePropertyChanged("Elevation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double KappaCoeffient {
            get {
                return this.KappaCoeffientField;
            }
            set {
                if ((this.KappaCoeffientField.Equals(value) != true)) {
                    this.KappaCoeffientField = value;
                    this.RaisePropertyChanged("KappaCoeffient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteAmplification {
            get {
                return this.SiteAmplificationField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteAmplificationField, value) != true)) {
                    this.SiteAmplificationField = value;
                    this.RaisePropertyChanged("SiteAmplification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoilCondition {
            get {
                return this.SoilConditionField;
            }
            set {
                if ((object.ReferenceEquals(this.SoilConditionField, value) != true)) {
                    this.SoilConditionField = value;
                    this.RaisePropertyChanged("SoilCondition");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TableServiceEntity", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.WindowsAzure.StorageClient")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.ServiceReference1.StationsInfo))]
    public partial class TableServiceEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartitionKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RowKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey {
            get {
                return this.PartitionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PartitionKeyField, value) != true)) {
                    this.PartitionKeyField = value;
                    this.RaisePropertyChanged("PartitionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RowKey {
            get {
                return this.RowKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.RowKeyField, value) != true)) {
                    this.RowKeyField = value;
                    this.RaisePropertyChanged("RowKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAzureStorage")]
    public interface IAzureStorage {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAzureStorage/AddMessage", ReplyAction="http://tempuri.org/IAzureStorage/AddMessageResponse")]
        bool AddMessage(ConsoleApplication1.ServiceReference1.QuakeMessage data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAzureStorage/GetStationsGroups", ReplyAction="http://tempuri.org/IAzureStorage/GetStationsGroupsResponse")]
        string[] GetStationsGroups();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAzureStorage/GetStations", ReplyAction="http://tempuri.org/IAzureStorage/GetStationsResponse")]
        ConsoleApplication1.ServiceReference1.StationsInfo[] GetStations(string PartitionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAzureStorage/GetResults", ReplyAction="http://tempuri.org/IAzureStorage/GetResultsResponse")]
        string[] GetResults(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAzureStorage/CreateGrid", ReplyAction="http://tempuri.org/IAzureStorage/CreateGridResponse")]
        bool CreateGrid(ConsoleApplication1.ServiceReference1.StationsInfo station, double MinLat, double MaxLat, double LatStep, double MinLon, double MaxLon, double LonStep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAzureStorage/UploadFile", ReplyAction="http://tempuri.org/IAzureStorage/UploadFileResponse")]
        bool UploadFile(string PartitionKey, string file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAzureStorage/CalculateGeometry", ReplyAction="http://tempuri.org/IAzureStorage/CalculateGeometryResponse")]
        ConsoleApplication1.ServiceReference1.QuakeMessage CalculateGeometry(ConsoleApplication1.ServiceReference1.QuakeMessage q);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAzureStorage/DeleteStation", ReplyAction="http://tempuri.org/IAzureStorage/DeleteStationResponse")]
        void DeleteStation(string PartitionKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAzureStorageChannel : ConsoleApplication1.ServiceReference1.IAzureStorage, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AzureStorageClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference1.IAzureStorage>, ConsoleApplication1.ServiceReference1.IAzureStorage {
        
        public AzureStorageClient() {
        }
        
        public AzureStorageClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AzureStorageClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AzureStorageClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AzureStorageClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddMessage(ConsoleApplication1.ServiceReference1.QuakeMessage data) {
            return base.Channel.AddMessage(data);
        }
        
        public string[] GetStationsGroups() {
            return base.Channel.GetStationsGroups();
        }
        
        public ConsoleApplication1.ServiceReference1.StationsInfo[] GetStations(string PartitionKey) {
            return base.Channel.GetStations(PartitionKey);
        }
        
        public string[] GetResults(string name) {
            return base.Channel.GetResults(name);
        }
        
        public bool CreateGrid(ConsoleApplication1.ServiceReference1.StationsInfo station, double MinLat, double MaxLat, double LatStep, double MinLon, double MaxLon, double LonStep) {
            return base.Channel.CreateGrid(station, MinLat, MaxLat, LatStep, MinLon, MaxLon, LonStep);
        }
        
        public bool UploadFile(string PartitionKey, string file) {
            return base.Channel.UploadFile(PartitionKey, file);
        }
        
        public ConsoleApplication1.ServiceReference1.QuakeMessage CalculateGeometry(ConsoleApplication1.ServiceReference1.QuakeMessage q) {
            return base.Channel.CalculateGeometry(q);
        }
        
        public void DeleteStation(string PartitionKey) {
            base.Channel.DeleteStation(PartitionKey);
        }
    }
}
